### ISSUE TITLE
Use new permission request method

### ISSUE THREAD

**Issue by rfc2822** [bitfireAT/icsx5#6]
Use https://developer.android.com/training/permissions/requesting#allow-system-manage-request-code instead of the legacy way.

This is not an important issue and rather a test for the new method. :)

**Comment by rfc2822** [comment]
Currently crashes:

```
    java.lang.IllegalStateException: LifecycleOwner at.bitfire.icsdroid.ui.CalendarListActivity@f242dd9 is attempting to register while current state is STARTED. LifecycleOwners must call register before they are STARTED.
        at androidx.activity.result.ActivityResultRegistry.register(ActivityResultRegistry.java:123)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:682)
        at androidx.activity.ComponentActivity.registerForActivityResult(ComponentActivity.java:691)
        at at.bitfire.icsdroid.PermissionUtils.getCalendarPermissionRequestLauncher(PermissionUtils.kt:16)
        at at.bitfire.icsdroid.ui.CalendarListActivity.onCreate$lambda-0(CalendarListActivity.kt:70)
```
