### ISSUE TITLE
Workaround needed for AppleWebObjects

### ISSUE THREAD

**Issue by devvv4ever** [bitfireAT/icsx5#62]
This has been reported by a user when adding certain calendars to ICSx5.

Adding: webcal://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/getTeamMeetingsWebcal?teamid=1457876 will throw an error:

HTTP 401 Apple WebObjects
java.io.IOException: HTTP 401 Apple WebObjects
    at at.bitfire.icsdroid.CalendarFetcher.fetchNetwork$icsx5_62_2_0_2_gplayRelease(CalendarFetcher.kt:179)
    at at.bitfire.icsdroid.CalendarFetcher.onRedirect(CalendarFetcher.kt:83)
    at at.bitfire.icsdroid.CalendarFetcher.fetchNetwork$icsx5_62_2_0_2_gplayRelease(CalendarFetcher.kt:171)
    at at.bitfire.icsdroid.CalendarFetcher.run(CalendarFetcher.kt:46)
    at java.lang.Thread.run(Thread.java:1012)

While calendars from the same source with different events work:

webcal://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/getTeamMeetingsWebcal?teamid=1458151
webcal://hhv-handball.liga.nu/cgi-bin/WebObjects/nuLigaHBDE.woa/wa/getTeamMeetingsWebcal?teamid=1457879

Not super urgent but we should take look at this if we can workaround this.

**Comment by devvv4ever** [comment]
"But it works in Thunderbird" – _original reporter_

I will check with the user again.
